---
- name: Complile war from source code
  hosts: all
  become: true
  vars:
    - user_name: devops
  tasks:
    - name: Check correct maven is installed
      ansible.builtin.dnf:
        name:
          - maven-amazon-corretto17-1:3.8.4-3.amzn2023.0.5.noarch
          - maven-amazon-corretto11-1:3.8.4-3.amzn2023.0.5.noarch
        state: absent
      when: (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023")

    - name: Exact maven version
      ansible.builtin.dnf:
        name:
          - java-1.8.0-amazon-corretto.x86_64
          - java-1.8.0-amazon-corretto-devel.x86_64
          - maven-amazon-corretto8.noarch
        state: present
      when: (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023")

    - name: Run mvn Clean
      ansible.builtin.command:
        argv:
          - /usr/bin/mvn
          - clean
      args:
        chdir: /home/devops/<repository>
      register: my_output
      changed_when: my_output.rc != 0

    - name: Run mvn install
      ansible.builtin.command:
        argv:
          - /usr/bin/mvn
          - install
      args:
        chdir: /home/devops/<repository>
        creates: /home/devops/<repository>/target/javawebapp.war
      register: deploy_output
      become: true
      become_user: "{{ user_name }}"

    - name: Get ouput
      ansible.builtin.debug:
        msg:
          - "{{ deploy_output }}"

    - name: Deploy war to tomcat on Amazon Linux 2023
      ansible.builtin.copy:
        src: /home/devops/<repository>/target/javawebapp.war
        dest: /var/lib/tomcat10/webapps/
        mode: '0755'
        remote_src: true
      when: (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023")

    - name: Deploy war to tomcat  on RHEL8
      ansible.builtin.copy:
        src: /home/devops/<repository>/target/javawebapp.war
        dest: /var/lib/tomcat/webapps/
        mode: '0755'
        remote_src: true
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version != "2023")
